FROM node:20.14

# WORKDIR /usr/app/frontend
WORKDIR /usr/app/todoapp/frontend

COPY frontend/package*.json .

RUN npm install

COPY frontend/ .

RUN npm run build

# EXPOSE 5173
# CMD node dist/index.js

EXPOSE 5173

# RUN npm run dev -- --host 0.0.0.0 --port 5173
ENTRYPOINT [ "npm" ]
# CMD [ "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173" ]
CMD [ "run", "dev", "--", "--host" ]