services:

    backend:
        build:
            context: ./
            dockerfile: ./dockerfile
            target: backend
        ports:
            - "3000:3000"
        volumes:
            - todoapp:/backend

    frontend:
        build:
            context: ./
            dockerfile: ./dockerfile
            target: frontend
        ports:
            - "5173:5173"
        volumes:
            - todoapp:/frontend

volumes:
  todoapp: