version: "3.8"
services:

    backend:
        build:
            context: /backend
            dockerfile: ./dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/go/src/app

    frontend:
        build:
            context: /frontend
            dockerfile: ./dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app