services:

    backend:
        build:
            context: ./
            dockerfile: ./dockerfile
            target: backend
        ports:
            - "3000:3000"
        volumes:
            - todoapp:/todoapp

    frontend:
        build:
            context: ./
            dockerfile: ./dockerfile
            target: frontend
        ports:
            - "5173:5173"
        volumes:
            - todoapp:/usr/app/todoapp

    # app:
    #     build:
    #         context: ./
    #         dockerfile: ./dockerfile
    #     ports:
    #         - "5173:5173"
    #         - "3000:3000"

volumes:
  todoapp: