name: main Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  conditional-test:
    if: contains(github.event.commits.*.message | join(' '), 'v.') # Vérifie la présence de 'v.' dans les messages de commit

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:ci
