name: Main Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  conditional-job:
    runs-on: windows-latest

    # Vérifie si le dernier message de commit contient 'v's

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci
