name: Workflow de Test

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  execution-tests-unitaire:
    runs-on: windows-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

  linting:
    runs-on: windows-latest

    steps:

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.17'

        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm run lint