name: Workflow de Deploiement

on:
  workflow_dispatch:

jobs:
  build-frontend-image:
    runs-on: windows-latest

    # Vérifie si le dernier message de commit contient 'v's

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: julienmares
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: |
          cd backend
          $DOCKER_TOKEN
          docker build -t backend:latest . 
          docker tag backend:latest julienmares/backend:latest

      - name: Push Docker image
        run: |
          docker push julienmares/my-app:latest