name: Workflow de Deploiement

on:
  workflow_dispatch:

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    # Vérifie si le dernier message de commit contient 'v's

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: audit packages
        run: |
          npm audit || (
            echo "Vulnérabilité(s) détectée(s), tentative de fix" &&
            npm audit fix
          )
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build frontend image
        run: |
          docker build -t todo-frontend:latest ./frontend/ 
          docker tag todo-frontend:latest ${{ secrets.DOCKER_USER }}/todo-frontend:latest
      - name: Build backend image
        run: |
          docker build -t todo-backend:latest ./backend/
          docker tag todo-backend:latest ${{ secrets.DOCKER_USER }}/todo-backend:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/todo-frontend:latest
          docker push ${{ secrets.DOCKER_USER }}/todo-backend:latest
