name: Workflow de Deploiement

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    # Vérifie si le dernier message de commit contient 'v's

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: |
          docker build -t todo:latest . 
          docker tag todo:latest ${{ secrets.DOCKER_USER }}/todo:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/todo:latest
