name: Workflow de Test

on:
  push:
    branches: [ "main" ]

jobs:
  execution-tests-unitaire:
    runs-on: windows-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17'

      - name: Install dependencies
        run: npm install

      - name: audit packages
        run: |
          npm audit || (
            echo "Vulnérabilité(s) détectée(s), tentative de fix" &&
            npm audit fix
          )        

      - name: Run tests
        run: |
          cd backend
          npm install
          npm run test:ci

  linting:
    runs-on: windows-latest

    steps:

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.17'

        - name: Install dependencies
          run: npm install

        - name: audit packages
          run: |
            npm audit || (
              echo "Vulnérabilité(s) détectée(s), tentative de fix" &&
              npm audit fix
            )
        
        - name: Run eslint
          run: npm run lint